### ISSUE TITLE
How to make a Half donut ?

### ISSUE THREAD

**Issue by didintern** [kris-ellery/donut-chart#1]
Hello,

I have the values from a form in an array and My calculation is something like this 
foreach($revenue as $key=> $val){ 
         $x = ($val/array_sum($revennue))*180;
}
SO $x contains the angle for the slice in 180 degree , How can I use your plugin to do a half pie chart 

Thanks in Advance

**Comment by kris-ellery** [comment]
This is the closest I could get - http://jsfiddle.net/Lo92n9a9/

Let me know if that works for you. The only thing I changed in JS is offset degree (-90), and circle degree to 180. Then adjusted a bunch of CSS.

I might add it as an option, but that will require some rewriting.
